@startwbs Project Management Tool
** [[https://bamanexclusive.github.io/ProjectManagementTool/core-functionalities Core Functionalities]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/task-management Task Management]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/resource-allocation Resource Allocation]]
** [[https://bamanexclusive.github.io/ProjectManagementTool/chaos-engineering Chaos Engineering Integration]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/fault-injection Fault Injection]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/resilience-testing Resilience Testing]]
** [[https://bamanexclusive.github.io/ProjectManagementTool/user-interface User Interface]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/dashboard Dashboard]]
*** [[https://bamanexclusive.github.io/ProjectManagementTool/reporting Reporting]]
@endwbs
