name: MVP Project Workflow

on:
  push:
    branches:
      - main
      - staging  # Add additional branches here

jobs:
  trigger-airflow-dag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Cache Python Dependencies
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 2: Log Start of Workflow
      - name: Log Start of Workflow
        run: echo "Starting MVP Project Workflow..."

      # Step 3: Trigger Apache Airflow DAG
      - name: Trigger Apache Airflow DAG
        run: |
          set -e  # Ensure the script exits on failure
          curl -X POST https://$AIRFLOW_SERVER/api/v1/dags/$DAG_ID/dagRuns \
          -H "Authorization: Bearer $AIRFLOW_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"conf": {}}'
        env:
          AIRFLOW_SERVER: ${{ secrets.AIRFLOW_SERVER }}
          AIRFLOW_TOKEN: ${{ secrets.AIRFLOW_TOKEN }}
          DAG_ID: ${{ secrets.DAG_ID }}

      # Step 4: Log Completion of Workflow
      - name: Log Completion of Workflow
        run: echo "MVP Project Workflow completed successfully."
